#!/bin/bash -e

python_wheel_dir="/usr/share/python-wheels"
pyserial_wheel_file="pyserial-3.4-py2.py3-none-any.whl"

pyserial_wheel_file_path="$python_wheel_dir/$pyserial_wheel_file"


download_wheel_if_missing()
{
	if [ ! -f "$pyserial_wheel_file_path" ]; then
		md5="0e555d61700e0b95a15d8162092c5299"
		pyserial_wheel_link="https://pypi.python.org/packages/0d/e4/2a744dd9e3be04a0c0907414e2a01a7c88bb3915cbe3c8cc06e209f59c30/$pyserial_wheel_file#md5=$md5"

		wget "$pyserial_wheel_link" --output-document="$pyserial_wheel_file_path"
	fi
}

install_from_wheel()
{
	pyserial_ver="$(pip3 freeze | grep "^pyserial" | awk -F'=' '{print $NF}')"
	if [ -z "$pyserial_ver" ]; then
		pip3 install "$pyserial_wheel_file_path" --upgrade
		return
	else
		dpkg --compare-versions "$pyserial_ver" lt 3.4
		invalid_version=$?
		if $invalid_version; then
			pip3 install "$pyserial_wheel_file_path" --upgrade
		fi
	fi
}

download_wheel_if_missing
install_from_wheel
